# Generated by Django 4.0.3 on 2022-04-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('merchant_id', models.CharField(max_length=100)),
                ('checkout_id', models.CharField(max_length=100)),
                ('result_desc', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
            ],
        ),
    ]
