# Generated by Django 4.0.3 on 2022-03-14 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.UUID('4a5275ed-466f-495b-9207-042381c60736'), max_length=100),
        ),
    ]
