# Generated by Django 4.0.3 on 2022-03-15 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.UUID('27cc3660-4bc5-4ae5-996a-1d33624fb8dd'), max_length=100),
        ),
    ]
