# Generated by Django 4.0.3 on 2022-04-11 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_deals',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.UUID('ad9a4737-23b6-4ccb-acb3-d93730758287'), max_length=100),
        ),
    ]
