# Generated by Django 4.0.3 on 2022-04-16 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_on_deals_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='postcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='town',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.UUID('c0ef1d6d-21d5-434a-8d6e-c445d2011559'), max_length=100),
        ),
    ]
