# Generated by Django 4.0.3 on 2022-04-25 08:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_notes_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.UUID('939ac48a-b023-47fb-b427-a831b746fed1'), max_length=100),
        ),
    ]
