# Generated by Django 4.0.3 on 2022-05-02 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.UUID('0b11b948-ec71-45d2-86f3-d220a53c2370'), max_length=100),
        ),
    ]
